import type { Metadata } from "next";
import ApolloWrapper from "./components/ApolloWrapper";
// import AuthProvider from "./components/AuthProvider";

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
      <html lang="en">
      <body
        className={``}
      >
        <ApolloWrapper>
        {children}
        </ApolloWrapper>
      </body>
    </html>


  );
}
